### PR TITLE
Add Spanish

### PR DESCRIPTION
**Pull request by jfzazo**
Another translation to the project. This time to Spanish.

### CODE REVIEW

**Comment by jelveh** [comment]
Thank you very much @jfzazo! This would be an amazing addition 💪

**Comment by jelveh** [comment]
@jfzazo could you please look into the CLA. We need that before I can merge :(

**Comment by jfzazo** [comment]
Done! Sorry that I did not pay attention to the license before.

**Comment by jelveh** [comment]
Thank you for your contribution @jfzazo.

**Comment by jelveh** [comment]
> Done! Sorry that I did not pay attention to the license before.

No worries at all :)

**Pull request merged**
