### PR TITLE
Temporal commit for issue #432

### PR DESCRIPTION
**Pull request by Koppeks**

### CODE REVIEW

**Comment by jelveh** [comment]
I just tested this and saving files is working as expected. Do you still have the issue when you switch to the main branch?

**Comment by Koppeks** [comment]
Yes, I am currently on the main branch and has the same behavior.

**Comment by jelveh** [comment]
do you have the same issue using a fresh account (e.g. using incognito)

I need @KernelDeimos help here.

**Comment by Koppeks** [comment]
I test it with incognito too and the issue persist.

**Comment by jelveh** [comment]
Thank you, I'll investigate further and sync back soon.

**Comment by jelveh** [comment]
I'm still having a tough time reproducing the file saving issue, but the good news is that your PR for template files works like a charm for me! ✌️

P.S. Your PR also uncovered a bug in the ContextMenu which is pretty cool.

**Comment by Koppeks** [comment]
> I'm still having a tough time reproducing the file saving issue
> 
What OS are you guys using to develop the app? I maybe wrong but if the issue only happens to me, it could be the system, I am currently using Ubuntu 24.04 lts.

> P.S. Your PR also uncovered a bug in the ContextMenu which is pretty cool.

I am good catching bugs :sunglasses: :bug: .

**Comment by jelveh** [comment]
> What OS are you guys using to develop the app? 

I use Mac, Eric uses Arch, and some contributors are using Windows. I tested on Windows as well and couldn't reproduce. Haven't tested on Ubuntu yet since I need a machine with that.

I think this PR is going very well, so let's finish this and maybe you could open a separate issue for the file write problem you're experiencing.

**Pull request closed without merging**
