### PR TITLE
Add Thai translation. https://github.com/HeyPuter/puter/issues/522

### PR DESCRIPTION
**Pull request by sysnajar**
https://github.com/HeyPuter/puter/issues/522

### CODE REVIEW

**Comment by jelveh** [comment]
Hello @sysnajar, could you please look into the [CLA](https://github.com/HeyPuter/puter/pull/523#issuecomment-2211620375) before I can review your code and merge it?

**Comment by sysnajar** [comment]
> Hello @sysnajar, could you please look into the [CLA](https://github.com/HeyPuter/puter/pull/523#issuecomment-2211620375) before I can review your code and merge it?

Hi @jelveh ,
 done.

**Comment by jelveh** [comment]
I think you used a different account to push commits (**owatapx**). Could you confirm CLA with that account as well. Thank you!

**Comment by owatapx** [comment]
> I think you used a different account to push commits (**owatapx**). Could you confirm CLA with that account as well. Thank you!

Thank you for letting me know.  
Done @jelveh

**Comment by jelveh** [comment]
Merged. Thank you for your contribution. A much needed improvement.

**Comment by owatapx** [comment]
Thank you @Nariman ***@***.***>.

**Pull request merged**
