### PR TITLE
File association format

### PR DESCRIPTION
**Pull request by rowin-C**
- Installed Tagify package
- Setup Tagify code in dev-center.js
- Changed "A comma-separated list of file type specifiers." to "A list of file type specifiers."
- added function that validates user input before submit and shows error

### CODE REVIEW

**Comment by jelveh** [comment]
Hi @rowin-C , I was about to test your PR. Is a new one coming or should I just go with this?

**Comment by rowin-C** [comment]
i removed the unnecessary tagify package , its coming from cdn, im making a new pr now

**Comment by jelveh** [comment]
Hi Rowan, I ran this locally and I love the new tagified input!
Could take a look at the merge conflict before I an proceed with more reviews?

**Comment by rowin-C** [comment]
sure I'll look into the conflict and let you know

**Comment by jelveh** [comment]
Sorry I merged this by accident. I'm still testing. Getting syntax errors when opening dev center

**Comment by rowin-C** [comment]
Can you show me the error , then I'll try to fix it.

**Pull request merged**
