### PR TITLE
Update da.js

### PR DESCRIPTION
**Pull request by Abhinav-Bansal751**
# Description

This pr solves issue #875 

Danish counterparts have been added .

### CODE REVIEW

**Comment by Abhinav-Bansal751** [comment]
@jelveh sir ,I can complete all translation task if you like.

**Comment by jelveh** [comment]
Hi @Abhinav-Bansal751 . I really appreciate your contributions. But as a quick note I'm adding a condition for the translator being fluent in the language (this is to make sure the nuances are observed when translating). Do you mind if I ask whether you're fluent in Danish?

**Comment by Abhinav-Bansal751** [comment]
No sir ,I am not fluent but i have used gpt ,google etc for translation

**Comment by jelveh** [comment]
Thank you @Abhinav-Bansal751, I appreciate it. However, I had to add this condition because we've had instances where the native speakers of the language complained about the inaccuracies (I personally used GPT to translate and it back fired unfortunately). So I'm going to keep this PR open until I can get a quick review from somebody who's fluent in the language. 

Thanks again.

**Comment by Abhinav-Bansal751** [comment]
Ok sure, np sir

**Pull request closed without merging**
