### PR TITLE
Close apps by clicking on icons (issue #944) + awesome animations!

### PR DESCRIPTION
**Pull request by arthur-adriansens**
I added the app-request from issue #944, and I added a small clicking animation on the taskbar icons, like on MacBooks or Windows

### CODE REVIEW

**Comment by arthur-adriansens** [comment]
There's only one small bug I can't seem to fix. In a very specific case, when you open Explorer and you haven't interacted with the window (which doesn't happen often), you have to click twice before the window hides. This problem happens **only with Explorer**, in all other apps you can hide the window on the first icon click. 

I found the cause though: for some weird reason, the "window-active" class is already there on all apps, except for when you open Explorer and didn't do anything with the window, then the window-active class is being removed somewhere. _I spend a long time searching, but didn't find it._

**Comment by jelveh** [comment]
Looks pretty awesome! I'm testing and will merge soon

**Comment by arthur-adriansens** [comment]
Nice, thank you so much! I'm searching for new ideas in the issues tab :)

**Comment by jelveh** [comment]
> I found the cause though: for some weird reason, the "window-active" class is already there on all apps, except for when you open Explorer and didn't do anything with the window, then the window-active class is being removed somewhere. I spend a long time searching, but didn't find it.

Thanks for bringing this to my attention. I'm trying to fix and push the patch for this and then merge everything.

**Comment by jelveh** [comment]
Fixed. Interesting bug: When a taskbar item is clicked, the click is also propagated to the desktop and clicking on a desktop would naturally take away the focus from all windows. This only happened with Explorer because the click would immediately bubble whereas with other apps, the app had to be opened first which takes, at the very least, a few milliseconds and by that time the app has taken the focus back.

**Comment by arthur-adriansens** [comment]
Nice! Thanks for the help, and sorry for creating an extra issue. I, too, noticed that the desktop was being clicked, and I tried to move the taskbar out of the desktop div, but I was scared something would be dependent on it being inside the desktop div 😅. Didn't realize that it was actually the cause!

**Comment by jelveh** [comment]
I'm just happy the fix was actually simple. Was fearing the worst 👀
This has also fixed a few downstream issues as well, such as the window stack order not being corrupted which is important. Thanks again ✌️

**Pull request merged**
