### PR TITLE
Update Arabic translations in ar.js

### PR DESCRIPTION
**Pull request by medelm1**
This pull request updates the Arabic localization file (`ar.js`) to ensure it aligns with the latest English translations in `en.js`. The goal was to address discrepancies such as missing translations, outdated entries, and ensure cultural appropriateness and accurate meanings were maintained throughout.

### Changes Made

- Added missing translations where applicable.
- Updated outdated or incorrect translations to match the current English version.
- Ensured all translations are culturally appropriate and maintain the intended meaning of the English text.

### Additional Notes

- Transliteration or translator notes were used where necessary to maintain fidelity to the original text.
- Verified each change against the source file (`en.js`) to guarantee consistency.

### Related Files

- `src/gui/src/i18n/translations/ar.js`: Updated Arabic translations.
- `src/gui/src/i18n/translations/en.js`: Reference file for English translations.

This update enhances the Arabic localization of the project, ensuring a more consistent and accurate user experience for Arabic-speaking users.

### CODE REVIEW

**Comment by jelveh** [comment]
Hi @medelm1, thank you very much for your contribution! Merged 🎉

**Comment by jelveh** [comment]
oh just as I was about merge. Any reason you closed it?

**Comment by medelm1** [comment]
I accidentally closed this request; I will reopen it now.

**Comment by jelveh** [comment]
Awesome! Thanks again for your contribution.

**Comment by medelm1** [comment]
Thank you! I'm glad to contribute. Let me know if there's anything else I can help with!

**Comment by jelveh** [comment]
We definitely appreciate any help. Whether it's code, documentation, or user support. All contributions are welcome 😇

**Pull request merged**
