### PR TITLE
Directions for Windows / Docker Composer 

### PR DESCRIPTION
**Pull request by bryanthaboi**
npm doesn't run it correctly (it seems like its working but only white screens) but docker composer through wsl2 (automatically installed these days) does the trick

### CODE REVIEW

**Comment by jelveh** [comment]
Thank you very much for your contribution! Merged 🎉

**Comment by bryanthaboi** [comment]
No problem! Made a video about it. https://youtu.be/gf7eBugidHc?si=mz6von52kJDRDTiw

**Comment by jelveh** [comment]
@bryanthaboi Thank you so much for this!! Sorry Windows installation was broken. I'm going to fix it.

**Comment by bryanthaboi** [comment]
Hey no problem i figured out what i needed to to try it out!

**Comment by KernelDeimos** [comment]
@bryanthaboi following [another mention](https://github.com/HeyPuter/puter/issues/432) of Windows support we've added a fix (d80f2fa847bfaef98dc8d482898f5c15f268e4bd) that should get `npm install && npm start` working under Windows as well.

**Comment by jelveh** [comment]
@bryanthaboi we now have a "media" channel on Discord and I posted your video there as well: https://discord.com/channels/1071986474041495705/1263689151212032011/1263954371389952082

**Pull request merged**
