### PR TITLE
Update translations.js to Hungarian lang

### PR DESCRIPTION
**Pull request by Szab54**

### CODE REVIEW

**Comment by jelveh** [comment]
Thank you very much for your contribution! Could you please look into the CLA before I can review and merge?

**Comment by jelveh** [comment]
> Okay, but what is CLA? Sorry

No worries at all. The CLA is mentioned 2 comments up ([here](https://github.com/HeyPuter/puter/pull/594#issuecomment-2229187040)) it basically allow us to accept your code contribution into our project.

**Comment by Szab54** [comment]
> [CLA assistant check](https://cla-assistant.io/HeyPuter/puter?pullRequest=594) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/HeyPuter/puter?pullRequest=594) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/HeyPuter/puter?pullRequest=594) it.

Accept

**Comment by jelveh** [comment]
Thanks again for your awesome contribution 😇

**Pull request merged**
