### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by BatsKikker**

### CODE REVIEW

**Comment by AtkinsSJ** [comment]
Hi there! Thanks for the translation. Please add `nl` to the lists in `translations.js` so that Puter can find it. :^)

Also, if you wouldn't mind converting the tabs to spaces, that would be good. If you look at your changes on GitHub, you can see some are using tabs and aren't guaranteed to line up.

**Comment by BatsKikker** [comment]
Welp I might have just messed something up, I this github is not my thing, my absolute apologies.

**Comment by BatsKikker** [comment]
Somehow some tabs got replaced with 4 spaces, I've fixed those. I've also updated the file to the latest standard as found in the main branch, and made a small edit to the English one.

**Comment by jelveh** [comment]
Thank you for your contribution @BatsKikker, awesome to have Puter in Dutch as well 🔥

**Pull request merged**
