### PR TITLE
Update fr.js

### PR DESCRIPTION
**Pull request by Zac0511**
I translated the new 2FA things (since they were in the `en.js` file), so they are in french.

### CODE REVIEW

**Comment by Zac0511** [comment]
Huh those `'` caracters seems to be broking the code...

**Comment by Zac0511** [comment]
Hmmm i think i broken the code... i'l try to repair it

**Comment by Zac0511** [comment]
Okay, the code is **completly broken** for the moment. I'l try to repair it later. Its because i was there was a lot of new words missing, so i tried updating from `en.js`, but i broke the code by trying to do this.

**Comment by Zac0511** [comment]
I think i'l work on this later, my head is starting to hurt

**Comment by Zac0511** [comment]
I'm patching more and more bugs, it will be ready soon...

**Review by lucasgames8957 — APPROVED** [review]
Stinky man has arrived!

**Comment by Zac0511** [comment]
All bugs patched ! Its ready to merge, and i have intergrated **every string** from [en.js](https://github.com/HeyPuter/puter/blob/main/src/i18n/translations/en.js), so it should work !

**Pull request merged**
