### PR TITLE
More forgiving submenus

### PR DESCRIPTION
**Pull request by Hiya-its-Aya**
#### Notes:
- This employs this jQuery plugin https://github.com/kamens/jQuery-menu-aim by [Ben Kramens](https://github.com/kamens), as suggested by @AtkinsSJ. The plugin itself was slightly modified in order to dynamically determine the `submenuDirection` variable for each time the menu appears.

### CODE REVIEW

**Comment by jelveh** [comment]
Thank you for this @Hiya-its-Aya, a very important feature for usability. Seems to be working exactly as requested in the issue 💪 
I'm going for more manual testing and then if no issues, merge.

**Comment by jelveh** [comment]
I wasn't able to find any issues. Awesome PR @Hiya-its-Aya 🔥

**Comment by Hiya-its-Aya** [comment]
Thank you!

**Comment by AtkinsSJ** [comment]
Awesome! 🎉

**Pull request merged**
