### PR TITLE
Update Kurdish language template

### PR DESCRIPTION
**Pull request by BryarGh**
I have updated the Kurdish language template and reviewed it, there may be still some minor issues with the translation but for this stage is good.

### CODE REVIEW

**Comment by jelveh** [comment]
Hi @BryarGh, thanks again for translating Puter into Kurdish. I used the original English version of the license header but kept the Kurdish credit to the translator (yourself).

**Comment by BryarGh** [comment]
@jelveh , Do you want me to make any change? Like updating the header and pulling the request once again? or you will add or change the header yourself?

**Comment by jelveh** [comment]
I already pushed a commit for you to take a look as well: https://github.com/HeyPuter/puter/pull/640/commits/c71774664667cecd37eab2a5914b8a2c1fd7ef22

Let me know if it looks good and I can merge ✌️

**Comment by BryarGh** [comment]
All Good , please merge..

**Comment by jelveh** [comment]
Done! Thanks again 🫡

**Pull request merged**
