### PR TITLE
Updated Urdu translations, added missing entries, and corrected inacc…

### PR DESCRIPTION
**Pull request by Zuhaib-Asif**
Updated Urdu translations, added missing entries, and corrected inaccuracies

### CODE REVIEW

**Comment by jelveh** [comment]
Hello @Zuhaib-Asif, thank you very much for your contribution. Could you please, look into the [CLA](https://github.com/HeyPuter/puter/pull/521#issuecomment-2211430144) before I can review and merge your changes?

**Comment by Zuhaib-Asif** [comment]
@jelveh Sure

**Comment by jelveh** [comment]
Merged. Thank you for your contribution 😇

**Comment by Zuhaib-Asif** [comment]
Thank you! It was a pleasure contributing to the project.

**Pull request merged**
