### PR TITLE
refactor: conditionally focus terminal if phoenix is active

### PR DESCRIPTION
**Pull request by kumaryogesh17**
Issue #453
Added conditional statement that checks whether the variable phoenix exists and whether the phoenix application is active. If both conditions are met, it sets focus to the terminal window.

### CODE REVIEW

**Comment by jelveh** [comment]
Thank you for the PR. Could look into the CLA before I can review/merge this.

**Comment by KernelDeimos** [comment]
What is this for? If this is suppressing an error we should determine the root cause instead.

**Comment by jelveh** [comment]
I'm closing this due to no response

**Review by Skandiakiwi13 — APPROVED** [review]
Help

**Pull request closed without merging**
