### PR TITLE
fix: Automatic Adjustment of Puter Windows to Stay Within Viewport on Browser Resize #12

### PR DESCRIPTION
**Pull request by meetqy**
`window-login` can also use this code.

### CODE REVIEW

**Comment by jelveh** [comment]
Thank you for the PR! 
While testing for usability, I realized that it would be a good idea that open windows "remember" their initial position before resizing so that if the browser is expanded again, open windows can be put back in their initial position. Additionally, once the browser is shrunken, if the user moves a window, it might be a good idea to "forget" about initial positions since the user has signalled their intention to modify the state of their desktop. 

The following displays the usability issue with not remembering the initial positions.

https://github.com/HeyPuter/puter/assets/1715019/02e07aa7-8d6a-4b50-ae7a-63b8079a9625

This will take some work, so let me know if you need help.

**Comment by meetqy** [comment]
okey, I can try it. I think we can also add that when the window is larger than the initial position, use the initial position to calculate the `radio`. Without waiting for the window to return to its original position.

**Comment by meetqy** [comment]
https://github.com/HeyPuter/puter/assets/18411315/efa4046a-ab43-4fa1-be5a-36e9a21d47cb

add original_window_position in global.js

**Comment by jelveh** [comment]
@meetqy this is looking great! I need to test a little more (it's an important feature) and I should be able to merge today. Thanks again! 💪

**Comment by jelveh** [comment]
Thank you @meetqy for your contribution. I couldn't find any issues. Merging 💪

**Pull request merged**
