### PR TITLE
Add a CI script to check translations are valid

### PR DESCRIPTION
**Pull request by AtkinsSJ**
Checks the following:
- Translation files are valid JS
- Each translation file is registered in translations.mjs
- Each translation's code matches its name
- Translation dictionaries only contain keys that exist in the English translation.

An example output for when things are right:
image

...and when various things are wrong:
image

On second thought I might have gone overboard with exclamation marks. :laughing:

### CODE REVIEW

**Comment by AtkinsSJ** [comment]
Decided to try making the project use JS modules instead, and that was pretty easy, so I've done that in #151 instead of the file-renaming hacks I had done here. That'll need merging first.

**Comment by jelveh** [comment]
> gone overboard with exclamation marks.

There is no such a thing !!!!!!

!!

**Comment by AtkinsSJ** [comment]
Rebased and undrafted!!!

**Comment by jelveh** [comment]
Very useful, thanks Sam!

**Pull request merged**
