### PR TITLE
refactor: adjust max_tokens for specific models

### PR DESCRIPTION
**Pull request by KenKout**
fix: fix issue when there is an assistant role

In #1030, since you're tracking [token](https://github.com/HeyPuter/puter/pull/1031#issuecomment-2529562456), that's why I have removed the part of code max_input_tokens
#1029, solved this issue

### CODE REVIEW

**Comment by KenKout** [comment]
## This is the json that hasn't been parsed
```json
{
    "messages": [
        {
            "role": "user",
            "content": "Hi"
        },
        {
            "role": "assistant",
            "content": "Hello! How can I help you today?"
        },
        {
            "role": "user",
            "content": "What can you do?"
        },
        {
            "role": "assistant",
            "content": "I can help you with a variety of tasks, such as answering questions, providing recommendations, and more. Feel free to ask me anything!"
        },
        {
            "role": "user",
            "content": "That's great! Can you tell me a joke?"
        }
    ]
}
```

## This is how it behaves, left side is after being changed, right side is current flow-code
image

**Comment by KernelDeimos** [comment]
Hi, thanks for the PR.

If you're deleting code, you've gotta tell me why to save me a bit of time. In any case it looks like the divide-by-4 count was only used for a legacy check of the count and doesn't need to be here anymore, so I'll merge this.

**Comment by KenKout** [comment]
> On a related note, how did you find the process of finding the right file to edit and making this change? Let me know if there's any documentation we could add that would have helped.

I just use search function to find anything contains claude/anthropic so I can trace back the bug. I usually trace back by searching so I don't need documentation lol. But I think current structure of this project is good enough for any dev to read and modify

> If you're deleting code, you've gotta tell me why to save me a bit of time. In any case it looks like the divide-by-4 count was only used for a legacy check of the count and doesn't need to be here anymore, so I'll merge this.

I have told the reason why I have deleted in the first message, perhaps I was unclear about that, I'm so sorry about that

**Comment by KernelDeimos** [comment]
> I have told the reason why I have deleted in the first message, perhaps I was unclear about that, I'm so sorry about that

You were clear enough, I think I got distracted reading the linked issue and forget to read the rest of the sentence 😅

**Pull request merged**
